version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 14.x
        commands:
            - echo "updating the container"
            - apt-get update -y
            - apt-get upgrade -y
    pre_build:
        commands:
            - echo "we are in the pre build phase"
            - cd UI/femsKepler
            - npm install --production
    build:
        commands:
            - echo "we are in the build block"
            - npm run build
    post_build:
        commands:
            - echo "we are in the post build phase"
artifacts:
  files:
    - '**/*'
  base-directory: 'psLightningViewer/build'